#!/bin/sh

export APP_NAME=
export ECR_REPO=
export SSH_DEPLOY_HOST=
export DEPLOY_FULLPATH=
export FORWARD_HTTP_URL=
export NATS_SERVER=
export DISCORD_WEBHOOK_URL=
export NATS_TOPIC=
export GITHUB_PROJECT_URL=
export GITHUB_PROJECT_URL_SSH=
export JENKINS_APP_NAME=
export JENKINS_SECRET_DEPLOYHOST_NAME=
export JENKINS_URL=
export JENKINS_USER=
export JENKINS_API_TOKEN=
